name: pymc-extras-test
channels:
- conda-forge
- nodefaults
dependencies:
- pymc>=5.19.1
- pytest-cov>=2.5
- pytest>=3.0
- dask
- xhistogram
- statsmodels
- pip
- pip:
  - blackjax
  - scikit-learn
  - better_optimize>=0.0.10
