name: pymc-extras-test
channels:
- conda-forge
- defaults
dependencies:
- pip
- pytest-cov>=2.5
- pytest>=3.0
- dask
- xhistogram
- statsmodels
- pip:
  - pymc>=5.19.1  # CI was failing to resolve
  - blackjax
  - scikit-learn
  - better_optimize>=0.0.10
